# clean controls
osc=yes
border=no
keep-open=yes

# behavior
save-position-on-quit=no
pause=yes

# good defaults
hwdec=auto
vo=gpu-next

# subtle polish
cursor-autohide=1000

# base size for all text
osd-font-size=36
sub-font-size=36

# force same font
osd-font='Comic Mono'
sub-font='Comic Mono'

# keep scaling consistent
sub-scale=1
osd-scale=1

# prevent subtitle auto scaling weirdness
sub-scale-by-window=no

# window behavior
force-window=yes
auto-window-resize=no
keepaspect-window=no

# initial max/open size
autofit=1280x720

# do not center/reposition on each playlist item
# geometry=50%:50%
