# clean controls
osc=yes
border=no
keep-open=yes

# behavior
save-position-on-quit=yes
pause=yes

# good defaults
hwdec=auto
vo=gpu-next

# subtle polish
cursor-autohide=1000

# base size for all text
osd-font-size=36
sub-font-size=36

# force same font
osd-font='Comic Mono'
sub-font='Comic Mono'

# keep scaling consistent
sub-scale=1
osd-scale=1

# prevent auto scaling weirdness
sub-scale-by-window=no
sub-scale-with-window=no
force-window=yes
autofit=1280x720
geometry=50%:50%
